// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/demo/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "demo"
                ],
                "summary": "List demo accounts available for local account selection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.DemoUserResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/products": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "List products with live inventory and queue availability",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.ProductResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/products/{productID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product with live inventory and queue availability",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/products/{productID}/alternatives": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "List available alternative products",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.ProductRecommendationResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/products/{productID}/queue-entries": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queue"
                ],
                "summary": "Join a product queue",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Canonical lowercase external user UUID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "maxLength": 128,
                        "minLength": 1,
                        "type": "string",
                        "description": "Scoped queue join idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.QueueEntryResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.QueueEntryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict; disabled queues return error.code queue_disabled",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/products/{productID}/queue-entry": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queue"
                ],
                "summary": "Get the current or latest queue entry",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Canonical lowercase external user UUID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.QueueEntryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "queue"
                ],
                "summary": "Cancel the current or latest queue entry",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Canonical lowercase external user UUID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/queue-attempts/{attemptID}/checkout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkout"
                ],
                "summary": "Start or replay checkout for an invited queue attempt",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Canonical lowercase external user UUID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Queue attempt UUID",
                        "name": "attemptID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.QueueEntryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Reports that the HTTP process is serving; does not check dependencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infrastructure"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/payment-events": {
            "post": {
                "description": "Disabled by default. Runtime registration requires GOODQUEUE_UNSAFE_PAYMENT_CALLBACK=true; do not expose publicly.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Process an unsafe unauthenticated demo payment callback",
                "parameters": [
                    {
                        "description": "Payment provider event",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PaymentEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PaymentEventResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/handler.PaymentEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.PaymentEventResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.PaymentEventResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/products/{productID}/stock-adjustments": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Apply an idempotent internal stock adjustment",
                "parameters": [
                    {
                        "maxLength": 128,
                        "minLength": 1,
                        "type": "string",
                        "description": "Product-scoped adjustment key",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Adjustment payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.StockAdjustmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.StockAdjustmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/internal/v1/queue-buffer-metrics": {
            "get": {
                "description": "Reports durable reservation conversion and wait-time metrics. Active rights are excluded from conversion.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Queue-buffer experiment metrics",
                "parameters": [
                    {
                        "type": "string",
                        "default": "168h",
                        "description": "Cohort duration (Go duration, 1m..2160h)",
                        "name": "window",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.QueueMetricsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Reports whether PostgreSQL responds within the configured timeout. Dependency errors are never exposed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infrastructure"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.QueueAttemptState": {
            "type": "string",
            "enum": [
                "waiting",
                "invited",
                "checkout",
                "purchased",
                "invite_expired",
                "checkout_expired",
                "payment_failed",
                "cancelled",
                "sold_out"
            ],
            "x-enum-varnames": [
                "QueueAttemptWaiting",
                "QueueAttemptInvited",
                "QueueAttemptCheckout",
                "QueueAttemptPurchased",
                "QueueAttemptInviteExpired",
                "QueueAttemptCheckoutExpired",
                "QueueAttemptPaymentFailed",
                "QueueAttemptCancelled",
                "QueueAttemptSoldOut"
            ]
        },
        "domain.RecommendationMode": {
            "type": "string",
            "enum": [
                "ai_semantic",
                "catalog_fallback"
            ],
            "x-enum-varnames": [
                "RecommendationModeSemantic",
                "RecommendationModeFallback"
            ]
        },
        "domain.RecommendationReason": {
            "type": "string",
            "enum": [
                "semantically_similar",
                "same_category_available",
                "available_now"
            ],
            "x-enum-varnames": [
                "RecommendationReasonSemantic",
                "RecommendationReasonSameCategory",
                "RecommendationReasonAvailable"
            ]
        },
        "handler.DemoUserResponse": {
            "type": "object",
            "required": [
                "display_name",
                "external_user_id"
            ],
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "external_user_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handler.PaymentEventRequest": {
            "type": "object",
            "required": [
                "attempt_id",
                "event_id",
                "outcome",
                "payment_reference",
                "provider"
            ],
            "properties": {
                "attempt_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "event_id": {
                    "type": "string"
                },
                "outcome": {
                    "type": "string",
                    "enum": [
                        "succeeded",
                        "failed"
                    ]
                },
                "payment_reference": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "handler.PaymentEventResponse": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "handler.ProductRecommendationResponse": {
            "type": "object",
            "required": [
                "allocatable_stock",
                "category",
                "description",
                "free_stock",
                "id",
                "image_url",
                "price_cents",
                "queue_enabled",
                "reserved",
                "title",
                "waiting_buffer_capacity",
                "waiting_count"
            ],
            "properties": {
                "allocatable_stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "free_stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "image_url": {
                    "type": "string",
                    "format": "uri"
                },
                "price_cents": {
                    "type": "integer",
                    "minimum": 0
                },
                "queue_enabled": {
                    "type": "boolean"
                },
                "reason_code": {
                    "enum": [
                        "semantically_similar",
                        "same_category_available",
                        "available_now"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.RecommendationReason"
                        }
                    ]
                },
                "recommendation_mode": {
                    "enum": [
                        "ai_semantic",
                        "catalog_fallback"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.RecommendationMode"
                        }
                    ]
                },
                "recommendation_score": {
                    "type": "number",
                    "maximum": 1,
                    "minimum": 0
                },
                "reserved": {
                    "type": "integer",
                    "minimum": 0
                },
                "title": {
                    "type": "string"
                },
                "waiting_buffer_capacity": {
                    "type": "integer",
                    "minimum": 0
                },
                "waiting_count": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "handler.ProductResponse": {
            "type": "object",
            "required": [
                "allocatable_stock",
                "category",
                "description",
                "free_stock",
                "id",
                "image_url",
                "price_cents",
                "queue_enabled",
                "reserved",
                "title",
                "waiting_buffer_capacity",
                "waiting_count"
            ],
            "properties": {
                "allocatable_stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "free_stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "image_url": {
                    "type": "string",
                    "format": "uri"
                },
                "price_cents": {
                    "type": "integer",
                    "minimum": 0
                },
                "queue_enabled": {
                    "type": "boolean"
                },
                "reserved": {
                    "type": "integer",
                    "minimum": 0
                },
                "title": {
                    "type": "string"
                },
                "waiting_buffer_capacity": {
                    "type": "integer",
                    "minimum": 0
                },
                "waiting_count": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "handler.QueueEntryResponse": {
            "type": "object",
            "required": [
                "attempt_id",
                "created_at",
                "message_code",
                "next_action",
                "product_id",
                "queue_sequence",
                "state",
                "updated_at"
            ],
            "properties": {
                "attempt_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "checkout_started_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "deadline_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "expires_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "invited_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "message_code": {
                    "type": "string"
                },
                "next_action": {
                    "type": "string"
                },
                "position": {
                    "type": "integer",
                    "minimum": 1
                },
                "position_ahead": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "purchased_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "queue_sequence": {
                    "type": "integer"
                },
                "state": {
                    "$ref": "#/definitions/domain.QueueAttemptState"
                },
                "terminal_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "total_waiting": {
                    "type": "integer",
                    "minimum": 0
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "handler.QueueMetricTotalsResponse": {
            "type": "object",
            "properties": {
                "active_rights": {
                    "type": "integer"
                },
                "average_queue_wait_seconds": {
                    "type": "number"
                },
                "cancelled_after_right": {
                    "type": "integer"
                },
                "checkout_expired": {
                    "type": "integer"
                },
                "invite_expired": {
                    "type": "integer"
                },
                "issued_rights": {
                    "type": "integer"
                },
                "joined_attempts": {
                    "type": "integer"
                },
                "payment_failed": {
                    "type": "integer"
                },
                "purchases": {
                    "type": "integer"
                },
                "resolved_right_conversion_percent": {
                    "type": "number"
                },
                "resolved_rights": {
                    "type": "integer"
                }
            }
        },
        "handler.QueueMetricsResponse": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.QueueProductMetricResponse"
                    }
                },
                "totals": {
                    "$ref": "#/definitions/handler.QueueMetricTotalsResponse"
                },
                "waiting_buffer_percent": {
                    "type": "integer"
                },
                "window_end": {
                    "type": "string"
                },
                "window_start": {
                    "type": "string"
                }
            }
        },
        "handler.QueueProductMetricResponse": {
            "type": "object",
            "properties": {
                "active_rights": {
                    "type": "integer"
                },
                "average_queue_wait_seconds": {
                    "type": "number"
                },
                "cancelled_after_right": {
                    "type": "integer"
                },
                "checkout_expired": {
                    "type": "integer"
                },
                "invite_expired": {
                    "type": "integer"
                },
                "issued_rights": {
                    "type": "integer"
                },
                "joined_attempts": {
                    "type": "integer"
                },
                "p95_queue_wait_seconds": {
                    "type": "number"
                },
                "payment_failed": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "product_title": {
                    "type": "string"
                },
                "purchases": {
                    "type": "integer"
                },
                "resolved_right_conversion_percent": {
                    "type": "number"
                },
                "resolved_rights": {
                    "type": "integer"
                }
            }
        },
        "handler.StockAdjustmentRequest": {
            "type": "object",
            "required": [
                "delta",
                "external_reference",
                "reason"
            ],
            "properties": {
                "delta": {
                    "type": "integer",
                    "example": 5
                },
                "external_reference": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "handler.StockAdjustmentResponse": {
            "type": "object",
            "properties": {
                "stock_after": {
                    "type": "integer"
                },
                "stock_before": {
                    "type": "integer"
                }
            }
        },
        "middleware.ErrorBody": {
            "type": "object",
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_input"
                },
                "message": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "middleware.ErrorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "$ref": "#/definitions/middleware.ErrorBody"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GoodQueue API",
	Description:      "REST API for a fair two-stage limited-product purchase queue.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
