package domain

import "errors"

var (
	ErrNotImplemented         = errors.New("not implemented")
	ErrNotFound               = errors.New("not found")
	ErrConflict               = errors.New("conflict")
	ErrInvalidInput           = errors.New("invalid input")
	ErrInvalidIdentity        = errors.New("invalid identity")
	ErrOutOfStock             = errors.New("out of stock")
	ErrInvitationExpired      = errors.New("invitation expired")
	ErrCheckoutExpired        = errors.New("checkout expired")
	ErrPaymentFailed          = errors.New("payment failed")
	ErrQueueSequenceExhausted = errors.New("queue sequence exhausted")
	ErrStaleClaim             = errors.New("stale worker claim")
	ErrPaymentClaimIntegrity  = errors.New("payment claim integrity violation")
	ErrInternal               = errors.New("internal error")
	ErrQueueDisabled          = errors.New("queue disabled")
	ErrAlreadyPurchased       = errors.New("already purchased")
	ErrQueueFull              = errors.New("queue full")
	ErrAttemptNotFound        = errors.New("queue attempt not found")
	ErrInvalidTransition      = errors.New("invalid queue transition")
	ErrAttemptGone            = errors.New("queue attempt expired or sold out")
	ErrAdjustmentConflict     = errors.New("stock adjustment idempotency conflict")
	ErrStockBelowReserved     = errors.New("stock cannot be below reserved")
	ErrStockBelowZero         = errors.New("stock cannot be below zero")
	ErrStockOverflow          = errors.New("stock exceeds supported range")
	ErrReservedInvariant      = errors.New("stored reserved inventory invariant violated")
)
